### ISSUE TITLE
Artigo Unisinos: Refletir sobre problemática da introdução

### ISSUE THREAD

**Issue by p3palazzo** [dmcpatrimonio/catetinho#1]
@marinamennucci : Redigi um rascunho da introdução e conclusão do [artigo para a revista da Unisinos](https://github.com/dmcpatrimonio/catetinho/blob/dev/ar-catetinho.md), adaptadas ao público brasileiro, para reflexão sobre os caminhos a serem seguidos no desenvolvimento. Vou traduzir o texto do congresso para aproveitar nas demais seções.

**Comment by marinamennucci** [comment]
UAU!
 
 



De: "Pedro P. Palazzo" <notifications@github.com>
Enviada: 2020/04/21 19:20:59
Para: catetinho@noreply.github.com
Cc:  marinam@uol.com.br, assign@noreply.github.com
Assunto:  [dmcpatrimonio/catetinho] Artigo Unisinos: Refletir sobre problemática da introdução (#1)
 

 

@marinamennucci : Redigi um rascunho da introdução e conclusão do artigo para a revista da Unisinos, adaptadas ao público brasileiro, para reflexão sobre os caminhos a serem seguidos no desenvolvimento. Vou traduzir o texto do congresso para aproveitar nas demais seções.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub, or unsubscribe.

[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/dmcpatrimonio/catetinho/issues/1", "url": "https://github.com/dmcpatrimonio/catetinho/issues/1", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by p3palazzo** [comment]
Migrando esta discussão para o #2 .
